version: '3.8'

services:

  mysqldb:
    image: mysql/mysql-server
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db-config:/etc/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/
      - ./db/backup/files/:/data_backup/data
    
  
volumes:
  db-config:
  db-data: