
//THIS IS THE LOGIN REQUEST
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}



###
GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYzODg0NjI4NSwiZXhwIjoxNjM4ODQ3MTg1fQ.X4MQhmB3Pl-QJtablY-tyGnkBJVfgyDtk6YtxeyhYzQ


###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYzODg0NjE0OX0.DlI_IM6zX3h5cm44bN6YvjBNJCPUwU8PZwl4VDqHCZo"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYzODg0NjI4NSwiZXhwIjoxNjM4ODQ3MTg1fQ.X4MQhmB3Pl-QJtablY-tyGnkBJVfgyDtk6YtxeyhYzQ"
}


//DO NOT USE THE REQUEST BELOW
###
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "Kyle"
}



{"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYzODg0NjE0OSwiZXhwIjoxNjM4ODQ3MDQ5fQ.2XIsSTh5hePkmhDsNzIfiYBYTluddHurvh1gkbj_F98","refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYzODg0NjE0OX0.DlI_IM6zX3h5cm44bN6YvjBNJCPUwU8PZwl4VDqHCZo"}
{"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYzODg0NjI4NSwiZXhwIjoxNjM4ODQ3MTg1fQ.X4MQhmB3Pl-QJtablY-tyGnkBJVfgyDtk6YtxeyhYzQ"}