# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Create env file
      env:
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        LOCAL_DATABASE: ${{ secrets.LOCAL_DATABASE }}
        LOCAL_DOCKER_PORT: ${{ secrets.LOCAL_DOCKER_PORT }}
        LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
        LOCAL_PORT: ${{ secrets.LOCAL_PORT }}
        LOCAL_ROOT_PASSWORD: ${{ secrets.LOCAL_ROOT_PASSWORD }}
        LOCAL_USER: ${{ secrets.LOCAL_USER }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
        SKIP_PREFLIGHT_CHECK: ${{ secrets.SKIP_PREFLIGHT_CHECK }}
      run: | 
          touch .env
          echo ACCESS_TOKEN_SECRET="$ACCESS_TOKEN_SECRET" >> .env
          echo LOCAL_DATABASE="$LOCAL_DATABASE" >> .env
          echo LOCAL_DOCKER_PORT="$LOCAL_DOCKER_PORT" >> .env
          echo LOCAL_HOST="$LOCAL_HOST" >> .env
          echo LOCAL_PORT="$LOCAL_PORT" >> .env
          echo LOCAL_ROOT_PASSWORD="$LOCAL_ROOT_PASSWORD" >> .env
          echo LOCAL_USER="$LOCAL_USER" >> .env
          echo NODE_ENV="$NODE_ENV" >> .env
          echo REFRESH_TOKEN_SECRET="$REFRESH_TOKEN_SECRET" >> .env
          echo SKIP_PREFLIGHT_CHECK="$SKIP_PREFLIGHT_CHECK" >> .env
    - run: npm test
